In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.randn(3, 4, 5)
print(x)

tensor([[[-0.9472,  0.6773,  0.3627, -0.3702, -1.1854],
         [ 1.1600,  0.2319,  0.6551,  1.5642,  0.4746],
         [-0.7196,  0.5176,  0.4392, -1.5576,  0.8660],
         [-0.9538,  0.9653,  1.2923, -1.0202,  0.6128]],

        [[ 0.4084, -0.5330,  1.2853,  0.1953,  0.0565],
         [-0.8993, -0.1841, -1.1287, -0.1066,  0.6786],
         [-0.9494,  1.4233, -1.1830,  0.9064,  0.6403],
         [-0.4087,  1.0857,  1.5364, -1.4511, -0.7189]],

        [[ 0.8181, -0.0922,  0.7077, -0.1874, -0.5136],
         [ 0.0890, -0.3398, -1.3160,  0.8897, -0.3398],
         [ 0.3115,  0.6381,  0.0297,  2.2523,  0.9966],
         [ 0.5441,  2.4574,  0.6706, -0.9289,  1.2986]]])


In [3]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
x.reshape(6, 10)

tensor([[-0.9472,  0.6773,  0.3627, -0.3702, -1.1854,  1.1600,  0.2319,  0.6551,
          1.5642,  0.4746],
        [-0.7196,  0.5176,  0.4392, -1.5576,  0.8660, -0.9538,  0.9653,  1.2923,
         -1.0202,  0.6128],
        [ 0.4084, -0.5330,  1.2853,  0.1953,  0.0565, -0.8993, -0.1841, -1.1287,
         -0.1066,  0.6786],
        [-0.9494,  1.4233, -1.1830,  0.9064,  0.6403, -0.4087,  1.0857,  1.5364,
         -1.4511, -0.7189],
        [ 0.8181, -0.0922,  0.7077, -0.1874, -0.5136,  0.0890, -0.3398, -1.3160,
          0.8897, -0.3398],
        [ 0.3115,  0.6381,  0.0297,  2.2523,  0.9966,  0.5441,  2.4574,  0.6706,
         -0.9289,  1.2986]])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
torch.mul(x, torch.ShortTensor([1, 4, 2, 2, 1]))

tensor([[[-0.9472,  2.7094,  0.7253, -0.7405, -1.1854],
         [ 1.1600,  0.9278,  1.3103,  3.1285,  0.4746],
         [-0.7196,  2.0704,  0.8785, -3.1151,  0.8660],
         [-0.9538,  3.8612,  2.5846, -2.0404,  0.6128]],

        [[ 0.4084, -2.1321,  2.5706,  0.3906,  0.0565],
         [-0.8993, -0.7362, -2.2574, -0.2132,  0.6786],
         [-0.9494,  5.6933, -2.3659,  1.8127,  0.6403],
         [-0.4087,  4.3427,  3.0727, -2.9022, -0.7189]],

        [[ 0.8181, -0.3689,  1.4154, -0.3747, -0.5136],
         [ 0.0890, -1.3591, -2.6321,  1.7794, -0.3398],
         [ 0.3115,  2.5523,  0.0594,  4.5046,  0.9966],
         [ 0.5441,  9.8297,  1.3412, -1.8578,  1.2986]]])

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
y = x * x
y.reshape(6, 10)

tensor([[8.9717e-01, 4.5880e-01, 1.3153e-01, 1.3707e-01, 1.4051e+00, 1.3456e+00,
         5.3796e-02, 4.2922e-01, 2.4468e+00, 2.2529e-01],
        [5.1776e-01, 2.6791e-01, 1.9292e-01, 2.4260e+00, 7.4996e-01, 9.0982e-01,
         9.3182e-01, 1.6701e+00, 1.0408e+00, 3.7554e-01],
        [1.6679e-01, 2.8411e-01, 1.6519e+00, 3.8138e-02, 3.1965e-03, 8.0874e-01,
         3.3876e-02, 1.2740e+00, 1.1362e-02, 4.6044e-01],
        [9.0142e-01, 2.0258e+00, 1.3994e+00, 8.2149e-01, 4.1002e-01, 1.6707e-01,
         1.1787e+00, 2.3604e+00, 2.1058e+00, 5.1680e-01],
        [6.6928e-01, 8.5055e-03, 5.0083e-01, 3.5107e-02, 2.6382e-01, 7.9146e-03,
         1.1544e-01, 1.7320e+00, 7.9153e-01, 1.1548e-01],
        [9.7013e-02, 4.0713e-01, 8.8097e-04, 5.0728e+00, 9.9319e-01, 2.9609e-01,
         6.0389e+00, 4.4970e-01, 8.6282e-01, 1.6864e+00]])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor([1.0, 2.0, 3.0], requires_grad = True)
z = torch.tensor([3.0, 4.0, 5.0], requires_grad = True)
t = torch.tensor([6.0, 7.0, 8.0], requires_grad = True)

y = x**3 + z - 75*t

gradients = torch.FloatTensor([1, 0.5, 2])
y.backward(gradients,retain_graph=True)

print(x.grad)
print(z.grad)
print(t.grad)

tensor([ 3.,  6., 54.])
tensor([1.0000, 0.5000, 2.0000])
tensor([ -75.0000,  -37.5000, -150.0000])


In [8]:
# Создайте единичный тензор размера 5x6
ones = torch.ones(5, 6)

In [9]:
# Переведите его в формат numpy
ones.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [10]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте

from torch import nn 
from torch import optim

x = torch.randn(2, 2)

linear = nn.Linear(2, 2)

In [11]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.2210, -0.1037],
        [ 0.6970, -0.3401]], requires_grad=True)
b:  Parameter containing:
tensor([-0.2685,  0.3987], requires_grad=True)


In [12]:
w1 = 5

In [13]:
y = x**w1 - 2 * x**2 + 5

In [14]:
criterion = nn.MSELoss()

In [15]:
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [16]:
optimizer.zero_grad()
pred = linear(x)
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  19.009666442871094


In [17]:
loss.backward()

In [18]:
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[-3.1184, -2.1856],
        [-2.3335, -1.5538]])
dL/db:  tensor([-4.8267, -3.7832])


In [19]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.2210, -0.1037],
        [ 0.6970, -0.3401]], requires_grad=True)
b:  Parameter containing:
tensor([-0.2685,  0.3987], requires_grad=True)


In [20]:
optimizer.step()

In [21]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.1898, -0.0818],
        [ 0.7204, -0.3245]], requires_grad=True)
b:  Parameter containing:
tensor([-0.2202,  0.4365], requires_grad=True)
